name: Create PRs for Multiple Repos

on:
  workflow_dispatch:
    inputs:
      title:
        description: 'PR Title'
        required: true
        default: 'Regular Deployment 5th February, 2025'
      headBranch:
        description: 'Source Branch'
        required: true
        default: 'dev'
      baseBranch:
        description: 'Target Branch'
        required: true
        default: 'main'
      repos:
        description: 'Comma-separated list of repositories'
        required: true
        default: 'repo1,repo2'

jobs:
  create-prs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up GitHub CLI
        run: |
          curl -sSL https://github.com/cli/cli/releases/download/v2.16.2/gh_2.16.2_linux_amd64.deb -o gh-cli.deb
          sudo dpkg -i gh-cli.deb
          gh --version

      - name: Run PR Creation Script
        run: |
          PR_TITLE="${{ github.event.inputs.title }}"
          HEAD_BRANCH="${{ github.event.inputs.headBranch }}"
          BASE_BRANCH="${{ github.event.inputs.baseBranch }}"
          REPOS="${{ github.event.inputs.repos }}"

          echo "PR Title: $PR_TITLE"
          echo "Source Branch: $HEAD_BRANCH"
          echo "Target Branch: $BASE_BRANCH"
          echo "Repositories: $REPOS"

          # Pass the repositories as arguments to the shell script
          ./create_prs.sh "$HEAD_BRANCH" "$BASE_BRANCH" "$PR_TITLE" $REPOS
